CREATE TABLE GeneralTable (TestYear SMALLINT,
OUTID VARCHAR (512) UNIQUE,
Birth SMALLINT,
SEXTYPENAME VARCHAR (256),
REGNAME VARCHAR (256),
AREANAME VARCHAR (512),
TERNAME VARCHAR (256),
REGTYPENAME VARCHAR (1024),
TerTypeName VARCHAR (256),
ClassProfileNAME VARCHAR (256),
ClassLangName VARCHAR (256),
EONAME TEXT,
EOTYPENAME VARCHAR (512),
EORegName TEXT,
EOAreaName VARCHAR (512),
EOTerName VARCHAR (512),
EOParent TEXT,
UkrTest VARCHAR (512),
UkrTestStatus VARCHAR (256),
UkrBall100 SMALLINT,
UkrBall12 SMALLINT,
UkrBall SMALLINT,
UkrAdaptScale SMALLINT,
UkrPTName TEXT,
UkrPTRegName TEXT,
UkrPTAreaName VARCHAR (512),
UkrPTTerName VARCHAR (256),
histTest VARCHAR (512),
HistLang VARCHAR (256),
histTestStatus VARCHAR (256),
histBall100 SMALLINT,
histBall12 SMALLINT,
histBall SMALLINT,
histPTName TEXT,
histPTRegName TEXT,
histPTAreaName VARCHAR (512),
histPTTerName VARCHAR (256),
mathTest VARCHAR (512),
mathLang VARCHAR (256),
mathTestStatus VARCHAR (256),
mathBall100 SMALLINT,
mathBall12 SMALLINT,
mathBall SMALLINT,
mathPTName TEXT,
mathPTRegName TEXT,
mathPTAreaName VARCHAR (512),
mathPTTerName VARCHAR (256),
physTest VARCHAR (512),
physLang VARCHAR (256),
physTestStatus VARCHAR (256),
physBall100 SMALLINT,
physBall12 SMALLINT,
physBall SMALLINT,
physPTName TEXT,
physPTRegName TEXT,
physPTAreaName VARCHAR (512),
physPTTerName VARCHAR (256),
chemTest VARCHAR (512),
chemLang VARCHAR (256),
chemTestStatus VARCHAR (256),
chemBall100 SMALLINT,
chemBall12 SMALLINT,
chemBall SMALLINT,
chemPTName TEXT,
chemPTRegName TEXT,
chemPTAreaName VARCHAR (512),
chemPTTerName VARCHAR (256),
bioTest VARCHAR (512),
bioLang VARCHAR (256),
bioTestStatus VARCHAR (256),
bioBall100 SMALLINT,
bioBall12 SMALLINT,
bioBall SMALLINT,
bioPTName TEXT,
bioPTRegName TEXT,
bioPTAreaName VARCHAR (512),
bioPTTerName VARCHAR (256),
geoTest VARCHAR (512),
geoLang VARCHAR (256),
geoTestStatus VARCHAR (256),
geoBall100 SMALLINT,
geoBall12 SMALLINT,
geoBall SMALLINT,
geoPTName TEXT,
geoPTRegName TEXT,
geoPTAreaName VARCHAR (512),
geoPTTerName VARCHAR (256),
engTest VARCHAR (512),
engTestStatus VARCHAR (256),
engBall100 SMALLINT,
engBall12 SMALLINT,
engDPALevel VARCHAR(256),
engBall SMALLINT,
engPTName TEXT,
engPTRegName TEXT,
engPTAreaName VARCHAR (512),
engPTTerName VARCHAR (256),
fraTest VARCHAR (512),
fraTestStatus VARCHAR (256),
fraBall100 SMALLINT,
fraBall12 SMALLINT,
fraDPALevel VARCHAR(256),
fraBall SMALLINT,
fraPTName TEXT,
fraPTRegName TEXT,
fraPTAreaName VARCHAR (512),
fraPTTerName VARCHAR (256),
deuTest VARCHAR (512),
deuTestStatus VARCHAR (256),
deuBall100 SMALLINT,
deuBall12 SMALLINT,
deuDPALevel VARCHAR(256),
deuBall SMALLINT,
deuPTName TEXT,
deuPTRegName TEXT,
deuPTAreaName VARCHAR (512),
deuPTTerName VARCHAR (256),
spaTest VARCHAR (512),
spaTestStatus VARCHAR (256),
spaBall100 SMALLINT,
spaBall12 SMALLINT,
spaDPALevel VARCHAR(256),
spaBall SMALLINT,
spaPTName TEXT,
spaPTRegName TEXT,
spaPTAreaName VARCHAR (512),
spaPTTerName VARCHAR (256));
