INSERT INTO Region(Region)
SELECT DISTINCT REGNAME
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT EORegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT UkrPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT histPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT mathPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT physPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT chemPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT bioPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT geoPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT engPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT fraPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT deuPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;

INSERT INTO Region(Region)
SELECT DISTINCT spaPTRegName
FROM GeneralTable
ON CONFLICT DO NOTHING;